# A Machine Learning Model to Predict Customer Churn

## **Project Description**
The goal of this project is to develop a supervised machine learning model to analyze customer attrition within the Vodafone telecom company. The model will utilize any provided dataset to generate new observations by accurately determining whether a customer is likely to churn or not. This initiative aims to provide valuable insights into customer behavior, enabling the identification of potential churn and facilitating strategic interventions to retain customers effectively. The outcome of the project will contribute to a more informed and proactive approach to customer relationship management within Vodafone.

#### The data set includes information about:

* Customers who left within the company  — the column is called Churn.
* Services that each customer has signed up for — phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
* Customer account information — how long they’ve been a customer (Tenure ), contract, payment method, paperless billing, monthly charges, and total charges
* Demographic info about customers — gender, age range, and if they have partners and dependents
Demographics
CustomerID: A unique ID that identifies each customer.
* Senior Citizen: Indicates if the customer is older: Yes, No
* Dependents: Indicates if the customer lives with any dependents: Yes, No. Dependents could be children, parents, grandparents, etc.
* Tenure in Months: Indicates the total amount of months that the customer has been with the company 
* total charges is  equal to each tenue times monthly charges.
* Multiple Lines: Indicates if the customer subscribes to multiple telephone lines with the company: Yes, No

## **Hypothesis Testing**


Null Hypothesis (H0):

* H0: There is no significant relationship between customer churn and the termination of their contract.

Alternative Hypothesis (H1):

* H1: There is a significant relationship between customer churn and the termination of their contract.







## **Analytical Questions**
1. What is the overall count of customers who have discontinued their services with the company?

2. Which contract type exhibits a higher number of customers who have left the company?

3. How does the rate of customer churn change in relation to the duration of their subscription? (Visualized with a line chart)

4. Is there a correlation between the total charges accrued by customers and the type of contract they have? (Visualized with a bar chart)
5. What are the preferred payment methods?

### Step1: Import Libraries

#### Import Libraries

In [1]:
import pyodbc     
from dotenv import dotenv_values    #import the dotenv_values function from the dotenv package
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 

warnings.filterwarnings('ignore')

### Step2: Data Loading
The data for this project is divided into three parts

#### First Data set 

The first dataset is stored in ä Mcrosoft Sql Server . I will  connect to it remotely by using the  **pyodbc** library .






In [2]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')

# Get the values for the credentials you set in the '.env' file
server = environment_variables.get("SERVER")
database = environment_variables.get("DATABASE")
username = environment_variables.get("USERNAME")
password = environment_variables.get("PASSWORD")

In [3]:
# Create a connection string
connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password};MARS_Connection=yes;MinProtocolVersion=TLSv1.2;"


In [4]:
# Use the connect method of the pyodbc library and connect to the server . 


connection = pyodbc.connect(connection_string)

In [5]:
# The sql query to get the data 

query = "SELECT * FROM dbo.LP2_Telco_churn_first_3000"

data1 = pd.read_sql(query, connection)

In [6]:
data1.head()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG  Female          False     True       False       1   
1  5575-GNVDE    Male          False    False       False      34   
2  3668-QPYBK    Male          False    False       False       2   
3  7795-CFOCW    Male          False    False       False      45   
4  9237-HQITU  Female          False    False       False       2   

   PhoneService MultipleLines InternetService OnlineSecurity  ...  \
0         False          None             DSL          False  ...   
1          True         False             DSL           True  ...   
2          True         False             DSL           True  ...   
3         False          None             DSL           True  ...   
4          True         False     Fiber optic          False  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0            False       False       False           False  Month-to-month   
1             True       False       False           False        One year   
2            False       False       False           False  Month-to-month   
3             True        True       False           False        One year   
4            False       False       False           False  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0             True           Electronic check      29.850000     29.850000   
1            False               Mailed check      56.950001   1889.500000   
2             True               Mailed check      53.849998    108.150002   
3            False  Bank transfer (automatic)      42.299999   1840.750000   
4             True           Electronic check      70.699997    151.649994   

   Churn  
0  False  
1  False  
2   True  
3  False  
4   True  

[5 rows x 21 columns]

###  Second Dataset

* The second dataset for this project was found on OneDrive and is in CSV format.
* This dataset will serve as the test dataset.

In [7]:
data2 = pd.read_csv(r"C:\Users\pasca\OneDrive\Desktop\PaccyDEM\LP2_Machine_Learning_Project\Telco-churn-second-2000.csv")

In [8]:
data2.head(2)

customerID gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7613-LLQFO   Male              0      No         No      12          Yes   
1  4568-TTZRT   Male              0      No         No       9          Yes   

  MultipleLines InternetService       OnlineSecurity         OnlineBackup  \
0           Yes     Fiber optic                   No                   No   
1            No              No  No internet service  No internet service   

      DeviceProtection          TechSupport          StreamingTV  \
0                   No                   No                  Yes   
1  No internet service  No internet service  No internet service   

       StreamingMovies        Contract PaperlessBilling     PaymentMethod  \
0                   No  Month-to-month              Yes  Electronic check   
1  No internet service  Month-to-month               No      Mailed check   

   MonthlyCharges TotalCharges  
0           84.45      1059.55  
1           20.40        181.8

### Third Dataset 
The third dataset is also called Testing Data set will used to test my models

In [9]:
testing_data = pd.read_csv(r"C:\Users\pasca\OneDrive\Desktop\PaccyDEM\LP2_Machine_Learning_Project\LP2_Telco-churn-last-2000.csv")

In [10]:
testing_data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5600-PDUJF    Male              0      No         No       6          Yes   
1  8292-TYSPY    Male              0      No         No      19          Yes   
2  0567-XRHCU  Female              0     Yes        Yes      69           No   
3  1867-BDVFH    Male              0     Yes        Yes      11          Yes   
4  2067-QYTCF  Female              0     Yes         No      64          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0                No             DSL             No  ...               No   
1                No             DSL             No  ...              Yes   
2  No phone service             DSL            Yes  ...              Yes   
3               Yes     Fiber optic             No  ...               No   
4               Yes     Fiber optic             No  ...              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes          No              No  Month-to-month              Yes   
1         Yes          No              No  Month-to-month              Yes   
2          No          No             Yes        Two year              Yes   
3          No          No              No  Month-to-month              Yes   
4         Yes         Yes             Yes  Month-to-month              Yes   

             PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Credit card (automatic)          49.50         312.7    No  
1  Credit card (automatic)          55.00        1046.5   Yes  
2  Credit card (automatic)          43.95        2960.1    No  
3         Electronic check          74.35         834.2   Yes  
4         Electronic check         111.15        6953.4    No  

[5 rows x 21 columns]

## Step3 : Data Inspecting 

### Data1

In [11]:
data1.head()             # Displaying the first few rows of the DataFrame 'data1' to inspect the data structure



customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG  Female          False     True       False       1   
1  5575-GNVDE    Male          False    False       False      34   
2  3668-QPYBK    Male          False    False       False       2   
3  7795-CFOCW    Male          False    False       False      45   
4  9237-HQITU  Female          False    False       False       2   

   PhoneService MultipleLines InternetService OnlineSecurity  ...  \
0         False          None             DSL          False  ...   
1          True         False             DSL           True  ...   
2          True         False             DSL           True  ...   
3         False          None             DSL           True  ...   
4          True         False     Fiber optic          False  ...   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0            False       False       False           False  Month-to-month   
1             True       False       False           False        One year   
2            False       False       False           False  Month-to-month   
3             True        True       False           False        One year   
4            False       False       False           False  Month-to-month   

  PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0             True           Electronic check      29.850000     29.850000   
1            False               Mailed check      56.950001   1889.500000   
2             True               Mailed check      53.849998    108.150002   
3            False  Bank transfer (automatic)      42.299999   1840.750000   
4             True           Electronic check      70.699997    151.649994   

   Churn  
0  False  
1  False  
2   True  
3  False  
4   True  

[5 rows x 21 columns]

In [12]:
data1.shape         # Checking the dimensions (number of rows and columns) of the DataFrame 'data1'



(3000, 21)

In [13]:
data1.info()             # Displaying concise information about the DataFrame 'data1', including data types and non-null values



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        3000 non-null   object 
 1   gender            3000 non-null   object 
 2   SeniorCitizen     3000 non-null   bool   
 3   Partner           3000 non-null   bool   
 4   Dependents        3000 non-null   bool   
 5   tenure            3000 non-null   int64  
 6   PhoneService      3000 non-null   bool   
 7   MultipleLines     2731 non-null   object 
 8   InternetService   3000 non-null   object 
 9   OnlineSecurity    2349 non-null   object 
 10  OnlineBackup      2349 non-null   object 
 11  DeviceProtection  2349 non-null   object 
 12  TechSupport       2349 non-null   object 
 13  StreamingTV       2349 non-null   object 
 14  StreamingMovies   2349 non-null   object 
 15  Contract          3000 non-null   object 
 16  PaperlessBilling  3000 non-null   bool   


##### Check for null values

In [51]:
data1.isnull().sum()

customerID            0
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines       269
InternetService       0
OnlineSecurity      651
OnlineBackup        651
DeviceProtection    651
TechSupport         651
StreamingTV         651
StreamingMovies     651
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges          5
Churn                 1
dtype: int64

###  Calculate and display the percentage of null values for each column in 'data1'


In [74]:
# Calculate the percentage of null values for each column in 'data1'
null_percentages = (data1.isnull().sum() / len(data1)) * 100

# Display the result
print("Percentage of null values for each column in 'data1':")
print(null_percentages)


Percentage of null values for each column in 'data1':
customerID           0.000000
gender               0.000000
SeniorCitizen        0.000000
Partner              0.000000
Dependents           0.000000
tenure               0.000000
PhoneService         0.000000
MultipleLines        8.966667
InternetService      0.000000
OnlineSecurity      21.700000
OnlineBackup        21.700000
DeviceProtection    21.700000
TechSupport         21.700000
StreamingTV         21.700000
StreamingMovies     21.700000
Contract             0.000000
PaperlessBilling     0.000000
PaymentMethod        0.000000
MonthlyCharges       0.000000
TotalCharges         0.166667
Churn                0.033333
dtype: float64


#### Check for duplicate 

In [75]:
data1.duplicated().sum()

0

In [76]:
data1.describe().T                # Generate descriptive statistics for numerical columns in 'data1' and transpose the result


count         mean          std        min         25%  \
tenure          3000.0    32.527333    24.637768   0.000000    9.000000   
MonthlyCharges  3000.0    65.347400    30.137053  18.400000   35.787499   
TotalCharges    2995.0  2301.278315  2274.987884  18.799999  415.250000   

                        50%          75%          max  
tenure            29.000000    56.000000    72.000000  
MonthlyCharges    70.900002    90.262501   118.650002  
TotalCharges    1404.650024  3868.725098  8564.750000

## Inspecting Column by column 
 however, only a subset of columns is presented for the sake of time constraints.


In [34]:
data1["tenure"].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39], dtype=int64)

In [37]:

result = data1[data1['tenure'] == 0]  # 0 means the customer has been with the company for less than one mont
result                                 #  This is due to the representation of tenure in months.



customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
488   4472-LVYGI  Female          False     True        True       0   
753   3115-CZMZD    Male          False    False        True       0   
936   5709-LVOEQ  Female          False     True        True       0   
1082  4367-NUYAO    Male          False     True        True       0   
1340  1371-DWPAZ  Female          False     True        True       0   

      PhoneService MultipleLines InternetService OnlineSecurity  ...  \
488          False          None             DSL           True  ...   
753           True         False              No           None  ...   
936           True         False             DSL           True  ...   
1082          True          True              No           None  ...   
1340         False          None             DSL           True  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies  Contract  \
488              True        True        True           False  Two year   
753              None        None        None            None  Two year   
936              True       False        True            True  Two year   
1082             None        None        None            None  Two year   
1340             True        True        True           False  Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
488              True  Bank transfer (automatic)      52.549999           NaN   
753             False               Mailed check      20.250000           NaN   
936             False               Mailed check      80.849998           NaN   
1082            False               Mailed check      25.750000           NaN   
1340            False    Credit card (automatic)      56.049999           NaN   

      Churn  
488   False  
753   False  
936   False  
1082  False  
1340  False  

[5 rows x 21 columns]

In [38]:
data1["PhoneService"].unique()

array([False,  True])

In [40]:
data1["MultipleLines"].unique()

array([None, False, True], dtype=object)

In [44]:
multuplelines_null_count = data1["MultipleLines"].isnull().sum()             # # Count the number of null values in the 'MultipleLines' column

multuplelines_null_count


269

In [45]:
data1["InternetService"].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [48]:
internet_service_count = data1['InternetService'].eq('No').sum()
internet_service_count

651

In [50]:
data1["OnlineSecurity"].unique()

array([False, True, None], dtype=object)

In [59]:
data1["StreamingMovies"].unique()

array([False, True, None], dtype=object)

In [60]:
data1["Contract"].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [61]:
data1.Contract.value_counts()      ## Count the occurrences of each unique value in the 'Contract' column and display the result


Contract
Month-to-month    1641
Two year           746
One year           613
Name: count, dtype: int64

In [64]:
data1["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [65]:
data1.PaymentMethod.value_counts()            ## Count the occurrences of each unique value in the 'paymentmethod' column and display the result

PaymentMethod
Electronic check             1004
Bank transfer (automatic)     687
Credit card (automatic)       657
Mailed check                  652
Name: count, dtype: int64

In [66]:
data1["MonthlyCharges"].unique()

array([29.85000038, 56.95000076, 53.84999847, ..., 33.90000153,
       34.        , 38.59999847])

In [68]:
data_Montlycharges = data1[data1["MonthlyCharges"]==34.] 
data_Montlycharges

customerID gender  SeniorCitizen  Partner  Dependents  tenure  \
2992  4177-JPDFU   Male          False    False       False      12   

      PhoneService MultipleLines InternetService OnlineSecurity  ...  \
2992         False          None             DSL          False  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
2992            False        True       False           False  Month-to-month   

     PaperlessBilling  PaymentMethod MonthlyCharges  TotalCharges  Churn  
2992            False   Mailed check           34.0    442.450012  False  

[1 rows x 21 columns]

In [69]:
data1["TotalCharges"].unique()

array([  29.85000038, 1889.5       ,  108.15000153, ..., 6143.14990234,
        144.80000305,  414.95001221])

In [70]:
data1["Churn"].unique() 

array([False, True, None], dtype=object)

In [73]:
data1["Churn"].isnull().sum()

1

In [72]:
data1.Churn.value_counts()

Churn
False    2219
True      780
Name: count, dtype: int64

## Data2

In [77]:
data2.head(15)           # Display the first 15 rows of the 'data2' DataFrame for a quick overview of the data.


customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0   7613-LLQFO    Male              0      No         No      12          Yes   
1   4568-TTZRT    Male              0      No         No       9          Yes   
2   9513-DXHDA    Male              0      No         No      27          Yes   
3   2640-PMGFL    Male              0      No        Yes      27          Yes   
4   3801-HMYNL    Male              0     Yes        Yes       1          Yes   
5   0516-QREYC  Female              1      No         No      24          Yes   
6   9685-WKZGT    Male              1      No         No      14          Yes   
7   6022-UGGSO  Female              1      No         No      32          Yes   
8   8084-OIVBS  Female              0      No         No      11          Yes   
9   8896-BQTTI    Male              0      No         No       1          Yes   
10  3865-QBWSJ    Male              1      No        Yes      38          Yes   
11  3352-RICWQ  Female              0     Yes        Yes       9          Yes   
12  2160-GPFXD    Male              0     Yes        Yes      54          Yes   
13  2065-MMKGR  Female              0      No         No      29          Yes   
14  5857-TYBCJ    Male              1     Yes         No      44          Yes   

   MultipleLines InternetService       OnlineSecurity         OnlineBackup  \
0            Yes     Fiber optic                   No                   No   
1             No              No  No internet service  No internet service   
2             No             DSL                  Yes                   No   
3            Yes     Fiber optic                   No                   No   
4             No     Fiber optic                   No                   No   
5             No              No  No internet service  No internet service   
6            Yes     Fiber optic                   No                   No   
7             No     Fiber optic                   No                  Yes   
8             No              No  No internet service  No internet service   
9            Yes              No  No internet service  No internet service   
10           Yes     Fiber optic                  Yes                   No   
11            No              No  No internet service  No internet service   
12           Yes             DSL                  Yes                  Yes   
13           Yes             DSL                   No                   No   
14           Yes     Fiber optic                   No                   No   

       DeviceProtection          TechSupport          StreamingTV  \
0                    No                   No                  Yes   
1   No internet service  No internet service  No internet service   
2                   Yes                  Yes                  Yes   
3                    No                  Yes                   No   
4                    No                   No                  Yes   
5   No internet service  No internet service  No internet service   
6                    No                   No                   No   
7                    No                   No                   No   
8   No internet service  No internet service  No internet service   
9   No internet service  No internet service  No internet service   
10                   No                   No                   No   
11  No internet service  No internet service  No internet service   
12                   No                  Yes                   No   
13                   No                   No                  Yes   
14                  Yes                   No                  Yes   

        StreamingMovies        Contract PaperlessBilling  \
0                    No  Month-to-month              Yes   
1   No internet service  Month-to-month               No   
2                   Yes        One year               No   
3                    No  Month-to-month              Yes   
4                   Yes  Month-to-month              

In [78]:
data2.shape             # Output the dimensions (number of rows and columns) of the 'data2' DataFrame.


(2000, 20)

In [18]:
data2.info()                   # Display concise information about the 'data2' DataFrame, including data types and non-null counts.


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2000 non-null   object 
 1   gender            2000 non-null   object 
 2   SeniorCitizen     2000 non-null   int64  
 3   Partner           2000 non-null   object 
 4   Dependents        2000 non-null   object 
 5   tenure            2000 non-null   int64  
 6   PhoneService      2000 non-null   object 
 7   MultipleLines     2000 non-null   object 
 8   InternetService   2000 non-null   object 
 9   OnlineSecurity    2000 non-null   object 
 10  OnlineBackup      2000 non-null   object 
 11  DeviceProtection  2000 non-null   object 
 12  TechSupport       2000 non-null   object 
 13  StreamingTV       2000 non-null   object 
 14  StreamingMovies   2000 non-null   object 
 15  Contract          2000 non-null   object 
 16  PaperlessBilling  2000 non-null   object 


#### Check for null values 

In [80]:
data2.isnull().sum()


customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

#### check for duplicate 

In [85]:
data2.duplicated().sum()

0

In [88]:
data2.describe().T

count       mean        std    min    25%   50%     75%  \
SeniorCitizen   2000.0   0.161500   0.368084   0.00   0.00   0.0   0.000   
tenure          2000.0  31.853000  24.632677   0.00   8.00  27.0  55.000   
MonthlyCharges  2000.0  63.933325  30.136858  18.25  34.25  69.8  89.275   

                   max  
SeniorCitizen     1.00  
tenure           72.00  
MonthlyCharges  118.75

In [87]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2000 non-null   object 
 1   gender            2000 non-null   object 
 2   SeniorCitizen     2000 non-null   int64  
 3   Partner           2000 non-null   object 
 4   Dependents        2000 non-null   object 
 5   tenure            2000 non-null   int64  
 6   PhoneService      2000 non-null   object 
 7   MultipleLines     2000 non-null   object 
 8   InternetService   2000 non-null   object 
 9   OnlineSecurity    2000 non-null   object 
 10  OnlineBackup      2000 non-null   object 
 11  DeviceProtection  2000 non-null   object 
 12  TechSupport       2000 non-null   object 
 13  StreamingTV       2000 non-null   object 
 14  StreamingMovies   2000 non-null   object 
 15  Contract          2000 non-null   object 
 16  PaperlessBilling  2000 non-null   object 


### Inspecting column by column 

In [97]:
data2["SeniorCitizen"].unique()             # Display unique values in the 'SeniorCitizen' column. I infer that 0 implies 'False' and 
                                            # 1 implies 'True' based on data1 and relevant literature.

array([0, 1], dtype=int64)

In [100]:
data2["tenure"].unique() 

array([12,  9, 27,  1, 24, 14, 32, 11, 38, 54, 29, 44, 59,  3, 18, 67, 22,
       33,  5,  2, 72, 16,  8, 23, 50, 17, 68, 25, 71, 46, 48, 61, 37, 65,
       49, 64, 21, 10,  6, 51, 47, 52, 35, 45,  4, 60, 28, 39, 30, 55, 58,
       26, 43, 56, 36, 13, 70, 69, 41, 15, 19, 31, 34, 66, 40,  7, 53, 63,
       42,  0, 57, 62, 20], dtype=int64)

In [101]:

result = data2[data2['tenure'] == 0]  # 0 means the customer has been with the company for less than one mont
result                                 #  This is due to the representation of tenure in months.



customerID  gender  SeniorCitizen Partner Dependents  tenure  \
331   7644-OMVMY    Male              0     Yes        Yes       0   
826   3213-VVOLG    Male              0     Yes        Yes       0   
1380  2520-SGTTA  Female              0     Yes        Yes       0   

     PhoneService MultipleLines InternetService       OnlineSecurity  \
331           Yes            No              No  No internet service   
826           Yes           Yes              No  No internet service   
1380          Yes            No              No  No internet service   

             OnlineBackup     DeviceProtection          TechSupport  \
331   No internet service  No internet service  No internet service   
826   No internet service  No internet service  No internet service   
1380  No internet service  No internet service  No internet service   

              StreamingTV      StreamingMovies  Contract PaperlessBilling  \
331   No internet service  No internet service  Two year               No   
826   No internet service  No internet service  Two year               No   
1380  No internet service  No internet service  Two year               No   

     PaymentMethod  MonthlyCharges TotalCharges  
331   Mailed check           19.85               
826   Mailed check           25.35               
1380  Mailed check           20.00

In [103]:
data2["MultipleLines"].unique() 

array(['Yes', 'No', 'No phone service'], dtype=object)

In [107]:

count_no_phone_service = data2['MultipleLines'].eq("No phone service").sum()

count_no_phone_service

193

In [109]:
data2.head(1)

customerID gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7613-LLQFO   Male              0      No         No      12          Yes   

  MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection  \
0           Yes     Fiber optic             No           No               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No         Yes              No  Month-to-month              Yes   

      PaymentMethod  MonthlyCharges TotalCharges  
0  Electronic check           84.45      1059.55

In [110]:
data2["InternetService"].unique() 

array(['Fiber optic', 'No', 'DSL'], dtype=object)

In [111]:
data2["OnlineSecurity"].unique() 

array(['No', 'No internet service', 'Yes'], dtype=object)

In [113]:

count_no_internet_service = data2['OnlineSecurity'].eq("No internet service").sum()

count_no_internet_service

446

In [114]:
data2["OnlineBackup"].unique() 

array(['No', 'No internet service', 'Yes'], dtype=object)

In [120]:
data2["StreamingMovies"].unique() 

array(['No', 'No internet service', 'Yes'], dtype=object)

In [121]:
data2["Contract"].unique()

array(['Month-to-month', 'One year', 'Two year'], dtype=object)

In [122]:
data2.Contract.value_counts()

Contract
Month-to-month    1131
Two year           451
One year           418
Name: count, dtype: int64

In [124]:
data2.head(1)

customerID gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7613-LLQFO   Male              0      No         No      12          Yes   

  MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection  \
0           Yes     Fiber optic             No           No               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No         Yes              No  Month-to-month              Yes   

      PaymentMethod  MonthlyCharges TotalCharges  
0  Electronic check           84.45      1059.55

In [125]:
data2["PaymentMethod"].unique()

array(['Electronic check', 'Mailed check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [126]:
data2.PaymentMethod.value_counts()

PaymentMethod
Electronic check             665
Mailed check                 484
Credit card (automatic)      432
Bank transfer (automatic)    419
Name: count, dtype: int64

In [127]:
data2["MonthlyCharges"].unique()

array([ 84.45,  20.4 ,  81.7 ,  79.5 ,  89.15,  20.3 ,  74.95,  74.4 ,
        20.  ,  25.  ,  80.45,  19.75,  65.65,  71.  ,  89.2 ,  86.75,
        55.3 ,  61.5 ,  25.1 ,  55.15,  34.05,  19.95,  89.7 ,  26.3 ,
        84.95,  20.7 ,  43.25,  48.35,  79.55,  71.05,  19.45, 110.8 ,
        84.5 ,  69.3 ,  49.35,  20.35, 105.6 ,  64.45, 108.6 ,  49.9 ,
        30.3 ,  30.4 ,  45.4 , 103.3 ,  84.15,  44.45,  85.4 ,  89.9 ,
        55.05, 104.1 , 106.6 ,  75.2 ,  70.5 ,  19.6 ,  55.85,  24.05,
        38.1 , 106.4 ,  34.25, 100.05,  68.65,  45.8 ,  75.75,  84.4 ,
        96.4 ,  20.55,  50.95,  90.5 ,  79.4 ,  58.75,  59.45, 105.7 ,
        56.25,  53.3 ,  85.55,  24.3 ,  77.85,  59.9 ,  23.95,  20.15,
       105.35,  95.65,  87.05,  81.  ,  82.45,  53.5 ,  20.5 ,  54.4 ,
        58.6 ,  84.8 ,  61.4 ,  79.65,  94.45,  79.8 ,  54.2 ,  74.05,
        49.15,  19.4 , 113.65, 106.  ,  25.95,  19.1 , 103.4 , 100.55,
        95.4 ,  75.15, 107.9 ,  19.5 ,  85.95,  24.95,  59.4 ,  69.95,
      

In [128]:
data2["TotalCharges"].unique()

array(['1059.55', '181.8', '2212.55', ..., '552.95', '7053.35', '301.55'],
      dtype=object)

### Data 3

In [130]:
testing_data.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5600-PDUJF    Male              0      No         No       6          Yes   
1  8292-TYSPY    Male              0      No         No      19          Yes   
2  0567-XRHCU  Female              0     Yes        Yes      69           No   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0                No             DSL             No  ...               No   
1                No             DSL             No  ...              Yes   
2  No phone service             DSL            Yes  ...              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes          No              No  Month-to-month              Yes   
1         Yes          No              No  Month-to-month              Yes   
2          No          No             Yes        Two year              Yes   

             PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Credit card (automatic)          49.50         312.7    No  
1  Credit card (automatic)          55.00        1046.5   Yes  
2  Credit card (automatic)          43.95        2960.1    No  

[3 rows x 21 columns]

In [131]:
testing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2043 entries, 0 to 2042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        2043 non-null   object 
 1   gender            2043 non-null   object 
 2   SeniorCitizen     2043 non-null   int64  
 3   Partner           2043 non-null   object 
 4   Dependents        2043 non-null   object 
 5   tenure            2043 non-null   int64  
 6   PhoneService      2043 non-null   object 
 7   MultipleLines     2043 non-null   object 
 8   InternetService   2043 non-null   object 
 9   OnlineSecurity    2043 non-null   object 
 10  OnlineBackup      2043 non-null   object 
 11  DeviceProtection  2043 non-null   object 
 12  TechSupport       2043 non-null   object 
 13  StreamingTV       2043 non-null   object 
 14  StreamingMovies   2043 non-null   object 
 15  Contract          2043 non-null   object 
 16  PaperlessBilling  2043 non-null   object 


In [133]:
testing_data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [134]:
testing_data.describe().T

count       mean        std    min     25%    50%     75%  \
SeniorCitizen   2043.0   0.168380   0.374295   0.00   0.000   0.00   0.000   
tenure          2043.0  32.649046  24.376248   0.00   9.000  30.00  55.000   
MonthlyCharges  2043.0  64.712555  29.970010  18.55  35.825  70.25  89.625   

                   max  
SeniorCitizen     1.00  
tenure           72.00  
MonthlyCharges  118.35

In [135]:
testing_data.head(1)

customerID gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5600-PDUJF   Male              0      No         No       6          Yes   

  MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0            No             DSL             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes          No              No  Month-to-month              Yes   

             PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Credit card (automatic)           49.5         312.7    No  

[1 rows x 21 columns]

In [141]:
testing_data["Dependents"].unique()

array(['No', 'Yes'], dtype=object)